Lecture 3 homework
ChepelVE/STA-with-Python pull request #3
Opened 2021-04-08 09:41 UTC by ChepelVE

2021-04-20 19:06 UTC, zhidelev requested changes
Поправить небольшие замечания и отправить снова на проверку 👍

2021-04-20 19:06 UTC, zhidelev commented on Lecture_3_FP_homework/task01/task01.py
> +        result.write(chr(10).join(lines_with_redirect))
Лучше не использовать `chr(10)` - неочевидно, что это за символ 😃 , лучше использовать `'\n'`, либо метод `writelines()` .

2021-04-20 19:06 UTC, zhidelev commented on Lecture_3_FP_homework/task02/task02.py
> +resp = get_joke(uri="/Spooky", params={'blacklistFlags': 'racist,sexist'})
Можно отправить ещё параметр `amount:10` - это максимум шуток в запросе.
И потом в респонсе из полученного json взять значение `amount` - там как раз будет количество отфильтрованных шуток (это относится к строке 33).

2021-04-21 06:56 UTC, ChepelVE commented on Lecture_3_FP_homework/task01/task01.py
> +        result.write(chr(10).join(lines_with_redirect))
сделал

2021-04-21 06:58 UTC, ChepelVE commented on Lecture_3_FP_homework/task02/task02.py
> +resp = get_joke(uri="/Spooky", params={'blacklistFlags': 'racist,sexist'})
сделал, но не совсем согласен.
- посчитать в моем понимании это не просто вывести то что отдает сервер
- параметр amount=10 не дефолтное значение
наверно не совсем верно понял задачу, возможно стоит ее чуть чуть переформулировать для будущих поколений))

2021-04-22 20:01 UTC, zhidelev commented on Lecture_3_FP_homework/task02/task02.py
> +resp = get_joke(uri="/Spooky", params={'blacklistFlags': 'racist,sexist'})
Сервер тоже может посчитать, такие возможности данного API. 
`amount=10` - это максимальное значение, по дефолту вроде 1.
Порефакторим 👍

2021-04-22 20:01 UTC, zhidelev approved these changes
Принято 👍

2021-04-23 07:00 UTC, merged