Lecture 4 homework
ChepelVE/STA-with-Python pull request #4
Opened 2021-04-10 09:38 UTC by ChepelVE

2021-04-20 18:50 UTC, zhidelev requested changes
Нужно поправить комментарии и отправить на проверку снова 👍

2021-04-20 18:50 UTC, zhidelev commented on Lecture_4_Testing_homework/test_cont_fraction.py
> +    assert cont_fraction(fraction) == expected
Добавь ещё тест с делением на 0. Как будет вести себя функция в таком случае?)

2021-04-20 18:50 UTC, zhidelev commented on Lecture_4_Testing_homework/continued_fraction.py
> +    fp = int(fraction.split("/")[1])
Можно сделать проще:
`ip, fp = map(int, inp.split("/"))`

2021-04-20 18:50 UTC, zhidelev commented on Lecture_4_Testing_homework/continued_fraction.py
> +        a = math.floor(ip / fp)
Остаток от деления можно сделать и без math.
`a = ip % fp`

2021-04-21 06:49 UTC, ChepelVE commented on Lecture_4_Testing_homework/continued_fraction.py
> +    fp = int(fraction.split("/")[1])
сделал

2021-04-21 06:49 UTC, ChepelVE commented on Lecture_4_Testing_homework/test_cont_fraction.py
> +    assert cont_fraction(fraction) == expected
добавил данные и try/except

2021-04-21 06:49 UTC, ChepelVE commented on Lecture_4_Testing_homework/continued_fraction.py
> +        a = math.floor(ip / fp)
тут округление

2021-04-22 20:55 UTC, zhidelev commented on Lecture_4_Testing_homework/continued_fraction.py
> +        a = math.floor(ip / fp)
тогда можно a = ip // fp

2021-04-22 21:02 UTC, zhidelev requested changes

2021-04-22 21:02 UTC, zhidelev commented on Lecture_4_Testing_homework/continued_fraction.py
> +            a = math.floor(ip / fp)
тогда можно `a = ip // fp`

2021-04-26 17:42 UTC, zhidelev approved these changes
👍

2021-04-27 09:30 UTC, merged