Lecture 6
ChepelVE/STA-with-Python pull request #6
Opened 2021-05-02 09:24 UTC by ChepelVE

2021-05-13 16:12 UTC, ZoiaOchikova requested changes

2021-05-13 16:12 UTC, ZoiaOchikova commented on Lecture_6_OOP2_homework/oop_2.py
> +    print('You are late')
Если нужно вывести какое-то сообщение, то можно передать его вот так, когда будешь бросать эксепшен: `DeadlineError('You are late')`

2021-05-13 16:12 UTC, ZoiaOchikova commented on Lecture_6_OOP2_homework/oop_2.py
> +        if len(value) > 5 and (key, value) not in self.homework_done.items():
У тебя получается, что если два студента сделали хорошо задание, то запишется результат только последнего из них.
И еще записывать в homework_done надо объекты типа HomeworkResult

2021-05-13 16:12 UTC, ZoiaOchikova commented on Lecture_6_OOP2_homework/oop_2.py
> +    def reset_results(*args):
Здесь ожидается максимум один аргумент, поэтому мне кажется удобнее передавать сразу этот аргумент с дефолтным значением.

2021-05-16 08:56 UTC, ChepelVE commented on Lecture_6_OOP2_homework/oop_2.py
> +    print('You are late')
переделал

2021-05-16 08:57 UTC, ChepelVE commented on Lecture_6_OOP2_homework/oop_2.py
> +        if len(value) > 5 and (key, value) not in self.homework_done.items():
переделал

2021-05-16 08:57 UTC, ChepelVE commented on Lecture_6_OOP2_homework/oop_2.py
> +    def reset_results(*args):
переделал

2021-05-20 13:38 UTC, ZoiaOchikova commented on Lecture_6_OOP2_homework/oop_2.py
> +        if len(value) > 5 and (key, value) not in self.homework_done.items():
В homework_done надо хранить объекты типа HomeworkResult. Результаты студентов все еще перезаписывают друг друга.

2021-05-22 09:08 UTC, ChepelVE commented on Lecture_6_OOP2_homework/oop_2.py
> +        if len(value) > 5 and (key, value) not in self.homework_done.items():
и вновь поправил)

2021-06-03 16:49 UTC, ZoiaOchikova approved these changes
зачет)

2021-06-04 11:12 UTC, merged